version: '2.1'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - /opt/docker-files/nginx-proxy/network_internal.conf:/etc/nginx/network_internal.conf
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      cloud-network:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion      
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      cloud-network:

  ncdb:
    image: mariadb:10.5.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qLwsPX9g4vQq
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=B7JtnBvv6rSg6Dug
    volumes:
      - ncdb-data:/var/lib/mysql
    networks:
      cloud-network:

  nc:
    image: nextcloud:19.0.1-apache
    restart: always
    depends_on:
      - ncdb
    volumes:
      - nc-nextcloud:/var/www/html
      - nc-apps:/var/www/html/custom_apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=B7JtnBvv6rSg6Dug
      - MYSQL_HOST=ncdb
      - VIRTUAL_HOST=cloud.admin-schule.de
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=cloud.admin-schule.de
      - LETSENCRYPT_EMAIL=info@admin-schule.de
      - RESOLVE_TO_PROXY_IP=true
    networks:
      cloud-network:
          
  office:
    image: collabora/code:4.2.6.2
    restart: always
    environment:
      - "domain=cloud\\.admin-schule\\.de"
      - "username=admin"
      - "password="
      - "SLEEPFORDEBUGGER=0"
      - VIRTUAL_HOST=office.admin-schule.de
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=office.admin-schule.de
      - LETSENCRYPT_EMAIL=info@admin-schule.de
      - RESOLVE_TO_PROXY_IP=true
      - NETWORK_ACCESS=internal
    expose:
      - 9980
    cap_add:
      - MKNOD
    networks:
      cloud-network:    
          
  networks:
    cloud-network:
      driver: bridge
          
  volumes:
    nginx-proxy-certs:
    nginx-proxy-vhost:
    ncdb-data:
    nc-nextcloud:
    nc-apps:
    nc-config:
    nc-data: