version: '2.1'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.9.1
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - /opt/docker-files/nginx-proxy/network_internal.conf:/etc/nginx/network_internal.conf
      - /opt/docker-files/nginx-proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      cloud-network:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.1
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      cloud-network:

  ncdb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TODO
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_user
      - MYSQL_PASSWORD=TODO
    volumes:
      - ncdb-data:/var/lib/mysql
    networks:
      cloud-network:

  ncredis:
    image: redis:6.0-buster
    restart: always
    command: redis-server --requirepass TODO
    networks:
      cloud-network:

  nc:
    image: nextcloud:stable
    restart: always
    depends_on:
      - ncdb
      - ncoffice 
      - ncredis
    volumes:
      - nc-nextcloud:/var/www/html
      - nc-apps:/var/www/html/custom_apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_user
      - MYSQL_PASSWORD=TODO
      - MYSQL_HOST=ncdb
      - VIRTUAL_HOST=lxcloud.derchef.site
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=lxcloud.derchef.site
      - LETSENCRYPT_EMAIL=mjindra@derchef.email
      - RESOLVE_TO_PROXY_IP=true
      - REDIS_HOST=ncredis
      - REDIS_HOST_PASSWORD=TODO
    networks:
      cloud-network:
              
  ncoffice:
    image: collabora/code:6.4.9.2
    restart: always
    environment:
      - "domain=lxcloud\\.derchef\\.site"
      - "username=derchef"
      - "password=TODO"
      - "SLEEPFORDEBUGGER=0"
      - VIRTUAL_HOST=docs.derchef.site
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=docs.derchef.site
      - LETSENCRYPT_EMAIL=mjindra@derchef.email
      - RESOLVE_TO_PROXY_IP=true
      - NETWORK_ACCESS=internal
    expose:
      - 9980
    cap_add:
      - MKNOD
    networks:
      cloud-network:

networks:
  cloud-network:
    driver: bridge
          
volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost:
  ncdb-data:
  nc-nextcloud:
  nc-apps:
  nc-config:
  nc-data:
