version: '2.1'
services:

  proxy:
    container_name: proxy
    image: "nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}"
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - ./nginx_config/network_internal.conf:/etc/nginx/network_internal.conf
      - ./nginx_config/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy}"

  letsencrypt_companion:
    container_name: letsencrypt_companion
    image: "nginxproxy/acme-companion:${NGINX_LETSENCRYPT_VERSION}"
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy

  nc_db:
    container_name: nc_db
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - nc-db-data:/var/lib/mysql

  redis:
    container_name: redis
    image: "redis:${REDIS_VERSION}"
    restart: always
    volumes:
      - redis:/var/lib/redis

  nc:
    container_name: nc
    image: "nextcloud:${NEXTCLOUD_VERSION}"
    restart: always
    depends_on:
      - proxy
      - letsencrypt_companion
      - nc_db
      - redis
      - nc_collabora
    volumes:
      - nc-nextcloud:/var/www/html
      - nc-apps:/var/www/html/custom_apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=nc_db"
      - "NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USER}"
      - "NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_USER_PASSWORD}"
      - "VIRTUAL_HOST=${NEXTCLOUD_DOMAIN}"
      - "VIRTUAL_PORT=80"
      - "VIRTUAL_PROTO=http"
      - "LETSENCRYPT_HOST=${NEXTCLOUD_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${NEXTCLOUD_EMAIL}"
      - "RESOLVE_TO_PROXY_IP=true"
      - "REDIS_HOST=redis"

  nc_collabora:
    container_name: nc_collabora
    image: "collabora/code:${COLLABORA_VERSION}"
    restart: always
    depends_on:
      - nc_db
      - redis
      - proxy
      - letsencrypt_companion
    environment:
      - "domain=${ESC_NEXCLOUD_DOMAIN}"
      - "username=${NEXTCLOUD_USER}"
      - "password=${NEXTCLOUD_USER_PASSWORD}"
      - "SLEEPFORDEBUGGER=0"
      - "VIRTUAL_HOST=${COLLABORA_DOMAIN}"
      - "VIRTUAL_PORT=9980"
      - "VIRTUAL_PROTO=https"
      - "LETSENCRYPT_HOST=${COLLABORA_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${NEXTCLOUD_EMAIL}"
      - "RESOLVE_TO_PROXY_IP=true"
      - "NETWORK_ACCESS=internal"
    expose:
      - 9980

  html_server:
    container_name: html_server
    image: "caddy:${CADDY_VERSION}"
    depends_on:
      - proxy
      - letsencrypt_companion
    volumes:
      - ./html_server/Caddyfile:/etc/caddy/Caddyfile
      - ./html_server/html:/usr/share/caddy/
    environment:
      - "VIRTUAL_HOST=${DOMAIN}"
      - "VIRTUAL_PORT=8080"
      - "LETSENCRYPT_HOST=${DOMAIN}"
      - "LETSENCRYPT_EMAIL=${NEXTCLOUD_EMAIL}"
    ports:
      - 8080:8080

volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost:
  redis:
  nc-db-data:
  nc-nextcloud:
  nc-apps:
  nc-config:
  nc-data:
